name: dev_toolkit
description: Dev Toolkit
version: 0.0.5

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  uuid: ^3.0.5
  flutter_redux: ^0.10.0
  redux: ^5.0.0
  flutter:
    sdk: flutter
  multicast_dns: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
