name: dev_toolkit
description: Dev Toolkit
version: 0.0.2
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  uuid: ^3.0.4
  flutter_redux: ^0.8.2
  redux: ^5.0.0
  flutter:
    sdk: flutter
  multicast_dns: ^0.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
